### ISSUE TITLE
Informacja o posiadaniu starej wersji SDK

### ISSUE THREAD

**Issue by bartcho** [soneta/Soneta.MsBuild.SDK#19]
Podczas build'u dodatku informować jako ostrzeżenie, że jest nowsza wersja SDK

**Comment by swiato** [comment]
Mechanizm informowania o nowszej wersji został zaimplementowany na branch'u **develop** i będzie dostępny w najbliższej wersji **Soneta.Sdk**. Jest on domyślnie wyłączony, aby go skonfigurować, należy użyć poniższych parametrów:

- **SonetaSdkUpdateIntervalTime** - domyślnie **None**, przyjmuje wartości z zakresu (**None, Seconds, Minutes, Hours, Days, Weeks, Months, Years**), ustawienie **None** powoduje wyłączenie mechanizmu informowania o nowej wersji, różne od **None** stanowi jednostkę czasu dla parametru **SonetaSdkUpdateIntervalValue**,

- **SonetaSdkUpdateIntervalValue** - przyjmuje wartości int, domyślnie 1, decyduje o wartości w konkretnej jednostce czasu zdefiniowanej przez **SonetaSdkUpdateIntervalTime**, od której zależy, jak często będą wykonywane odpytania do serwera o aktualny numer wersji Sdk.

Mechanizm ten zadziała tylko w przypadku, gdy istnieje plik **global.json** z odpowiednim wpisem dla **Soneta.Sdk**, zawierającym jego numer wersji. To z nim, porównywany jest numer Sdk pobrany z serwera (nuget api).

Przykładowo, jeśli sprawdzenie nowej wersji powinno następować co drugi dzień, wystarczy ustawić parametr 

```
<SonetaSdkUpdateIntervalTime>Days</SonetaSdkUpdateIntervalTime>
<SonetaSdkUpdateIntervalValue>2</SonetaSdkUpdateIntervalValue>
```
