### ISSUE TITLE
Brak możliwości uruchamiania na własnych konfiguracjach

### ISSUE THREAD

**Issue by MrSlynx** [soneta/Soneta.MsBuild.SDK#26]
Nie można automatycznie uruchomić enovy na konfiguracji innej niż 'Debug'.
Chciałem zrobić poprawkę (pull request), ale brak uprawnień.
Proste rozwiązanie:
```XML
<PropertyGroup Condition="($(Configuration) == 'Debug' OR $(CustomStartConfigurations.Contains($(Configuration)))) AND '$(IsTestProject)' != 'true' AND $(StartProgram) == '' AND Exists($(SonetaAddonStartProgram))">
```
[Miejsce](https://github.com/soneta/Soneta.MsBuild.SDK/blob/develop/src/Soneta.Sdk/Sdk/Sdk.targets#L5)
Możliwość dodania własnych konfiguracji uruchamiania poprzez element 'CustomStartConfigurations'
Przykładowo:
```XML
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <SonetaPackageVersion>1908.0.1</SonetaPackageVersion>
    <SonetaTargetFramework>net46</SonetaTargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CustomStartConfigurations>Local;Custom;Debug</CustomStartConfigurations>
  </PropertyGroup>
</Project>
```

**Comment by a4099181** [comment]
> Chciałem zrobić poprawkę (pull request), ale brak uprawnień.

@MrSlynx Brak uprawnień do czego? Czego nie udało się zrobić? Chętnie pochylimy się i odniesiemy do PR. Tymczasem nie widzę _fork_-a, na którym próba poprawki byłaby podjęta.

**Comment by bartcho** [comment]
Bardzo dziękujemy za sugestię zamiany. 
Zainspirowani nią proponujemy jeszcze prostsze rozwiązanie #29 . 
Planujemy je zrealizować w następnym sprincie.
