### ISSUE TITLE
automatyczne "wyliczanie" ścieżki do SonetaExplorer.exe

### ISSUE THREAD

**Issue by Infotelecom** [soneta/Soneta.MsBuild.SDK#3]
Obecny sposób, polegający na pobieraniu ostatniego podkatalogu w lokalizacji: 
c:\program files (x86)\Soneta 
chyba nie jest najlepszy.

Kiedy zostanie opublikowana nowsza wersja to w jaki sposób będzie można uruchomić poprzednią?
A co jeśli ktoś ma program zainstalowany w innej ścieżce niż domyślna?
Można oczywiście podać ścieżkę ręcznie ale wtedy będzie to zapisane w projekcie a tego chyba lepiej unikać.
Może dałoby się przeszukać Modules.xml i wziąć taką ścieżkę która zawiera fragment odpowiadający wybranej wersji?

**Comment by bartcho** [comment]
https://github.com/soneta/Soneta.MsBuild.SDK#informacje-og%C3%B3lne parametr SonetaAddonStartProgram
