### ISSUE TITLE
W ścieżce nie może być spacji, inaczej wywala  System.IO.DirectoryNotFoundException:

### ISSUE THREAD

**Issue by LukasMo** [soneta/Soneta.MsBuild.SDK#40]
Przykład na pustym projekcie Soneta.Addon (SDK) VS2019, Enova 2002.1.1

System.IO.DirectoryNotFoundException: 'Nie można odnaleźć części ścieżki „C:\Users\plan\Desktop\Dzien”.' zamiast "C:\Users\plan\Desktop\Dzien 2"
![Błąd ścieżki](https://user-images.githubusercontent.com/18001831/76504810-afea1d00-6448-11ea-9158-f52a11b0fa46.PNG)

 Po zmianie sciezki na „C:\Users\plan\Desktop\Dzien2\...”. wszystko smiga.

**Comment by a4099181** [comment]
Właściwa poprawka jest zaproponowana #45
