### ISSUE TITLE
Projekt z Soneta.MsBuild.SDK - ścieżka output

### ISSUE THREAD

**Issue by jac-czerwinski** [soneta/Soneta.MsBuild.SDK#41]
Dla projektu (a właściwie Solution) wygenerowanego "nowy sposobem" *) jak na razie wykryłem następujące braki:

a) Ścieżka Output ustawiona w typowe miejsce C:\Program Files (x86)\Common Files\Soneta\Assemblies w rzeczywistości skutkuje
C:\Program Files (x86)\Common Files\Soneta\Assemblies/net46

Musiałem zastosować w projekcie
```
<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
```

**Comment by jac-czerwinski** [comment]
*) mam na myśli Dobre praktyki tworzenia dodatków - Rafał Zięba

**Comment by damdyn** [comment]
Po pierwsze kompilacja do wspólnego katalogu dodatków nie jest zalecana, ponieważ nie mamy pełnej kontroli nad tym co konkretnie w danej chwili chcemy uruchomić.  Zalecane podejście to uruchomienie aplikacji z parametrem /extpath="lokalizacjaDodatku" wskazującym lokalizacje dodatku z , którym na zostać uruchomiona enova365.

Nie jest to brak tylko domyślne działanie, flaga AppendTargetFrameworkToOutputPath nie pochodzi z Soneta.MsBuild.SDK, więc nie została ujęta w początkowej wersji dokumentacji. 
Ze względu na to że faktycznie sporo osób będzie chciało ją wykorzystać została dodana tutaj:
#44
