### ISSUE TITLE
Projekt z Soneta Build Sdk - wersja Assembly się nie zmienia 

### ISSUE THREAD

**Issue by jac-czerwinski** [soneta/Soneta.MsBuild.SDK#42]
Projekty nowego typu nie dają kroczącej wersji Assembly. Cierpią na tym jak wiadomo m.in. PageFormsy 

1. Dałem
<Deterministic>false</Deterministic>

2. Na kilka sposobów próbowałem wsadzić gwiazdkę do AssemblyVersion, ale albo było to nielegalnie (VS odrzucało), albo nie skutkowało kroczącą wersją.

Nie uzyskałem rozwiązania. Po ręcznej zmianie na ostatnim segmencie wersji dodatki się odświeżają.

**Comment by bartcho** [comment]
To zgłoszenie jest chyba nie do tego repozytorium.
Prawidłowe repozytorium oraz zgłoszenie, którego dotyczy temat jest tu https://github.com/dotnet/roslyn/issues/33610
