### ISSUE TITLE
Błędne wykrywanie projektu testowego - niezgodność z dokumentacją

### ISSUE THREAD

**Issue by SylwesterZarebski** [soneta/Soneta.MsBuild.SDK#51]
Dokumentacja i wykrywanie projektu testowego są niezgodne ze sobą:
Dokumentacja opisuje
> Projekt testowy, który w swojej nazwie będzie zawierał słowo "**Tests**"

Zaś w `Sdk.props` jest:
```
<IsTestProject Condition="$(IsTestProject) == '' AND $(MSBuildProjectName.Contains('Test'))">true</IsTestProject>
```

Test<ins>***s***</ins> != Test

Moim zdaniem powinno się zmodyfikować wykrywanie na `Contains('Tests')`, bo fraza ***Test*** jest zbyt ogólną i wiele projektów miewa ***Test*** w nazwie projektu, ale nie jest projektem testowym.

PS. Wydaje się, że najlepszą konstrukcją powinno być `EndsWith('Tests')`, zamiast `Contains()`.

**Comment by bartcho** [comment]
Warunek Contains('Test') jest od początku istnienia SDK.
W przypadku bibliotek z Test w nazwie zawsze można jawnie w takim projekcie ustawić <IsTestProject>false</IsTestProject>, wtedy konwencja nie będzie miała znaczenia, bo Condition wyleci na pierwszym warunku.
Np u nas w repozytorium projekty testowe kończą się na Test, natomiast projekt wspomagający testowanie Soneta.Test nie jest projektem testowym i ma jawnie ustawione, że nie jest projektem testowym.

Biorąc powyższe pod uwagę proponuję, aby raczej iść w kierunku aktualizacji dokumentacji do tego co jest w Sdk,props

**Comment by SylwesterZarebski** [comment]
Więc poza poprawieniem dokumentacji można by zrobić `EndsWith`. Być może też warto by testować nie samą frazę `Test`, a `.Test` (z kropką). W komplecie by było `EndsWith('.Test')`.
