### ISSUE TITLE
nie działają testy w 1.1.3

### ISSUE THREAD

**Issue by DudaLuk** [soneta/Soneta.MsBuild.SDK#66]
z ustawieniem w global.json

{
  "msbuild-sdks": {
    "Soneta.Sdk": "1.1.3"
  }
}

nie uruchamiają się testy 
![obraz](https://user-images.githubusercontent.com/89943288/201073421-666cd7a1-c15d-4e7b-91ba-9026e28003dd.png)

po zmianie na 

{
  "msbuild-sdks": {
    "Soneta.Sdk": "1.1.2"
  }
}

![obraz](https://user-images.githubusercontent.com/89943288/201074211-cfceb9ee-9991-495f-8783-9106731e534d.png)

**Comment by SebastianWabnik** [comment]
A jakie masz ustawienia w projekcie ?
Ja mam takie jak poniżej i nie mam problemów

`<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Soneta.Sdk">
  <PropertyGroup>
    <TargetFramework>$(SonetaTargetFramework)</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="5.10.0" />
    <PackageReference Include="Moq" Version="4.16.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Soneta.Wsparcie\Soneta.Wsparcie.csproj" />  </ItemGroup>
</Project>
`

![image](https://user-images.githubusercontent.com/28555814/202723053-790c67a3-60e2-4d82-aabf-16762f9027b3.png)

![image](https://user-images.githubusercontent.com/28555814/202723141-990c8037-bfd7-4589-a8f4-bfbfe523d1d0.png)

**Comment by DudaLuk** [comment]
Cześć dzięki za odpowiedź 

```xml
<?xml version="1.0" encoding="utf-8"?>

<Project Sdk="Soneta.Sdk">
  <PropertyGroup>
    <TargetFramework>$(SonetaTestsTargetFramework)</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\sonetaaddon1\sonetaaddon1.csproj" />
  </ItemGroup>
</Project>


```
to w sumie czysty projekt jest 
https://github.com/DudaLuk/TestyProblem.git

**Comment by SebastianWabnik** [comment]
Cześć,
SDK dostarczyło nową wersję testAdaptera, ale jeszcze nie wiem z jakich powodów nie dostarczyło nowej wersji NUnit
Tymczasowo dodaj do projektu te sztywne referencje. A ja będę dalej analizował
`<ItemGroup>
    <PackageReference Include="NUnit" Version="3.13.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="NUnit3TestAdapter" Version="4.3.1" />
  </ItemGroup>`

**Comment by SebastianWabnik** [comment]
To jest problem lini framework. W lini net6 nie ma problemu - skonsultuje na spotkaniu czy będziemy z tym coś robić
